apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: injiverify
  labels:
    app: postgres
data:
  database-host: "postgres-postgresql.postgres"
  database-port: "5432"
  database-username: "verifyuser"
  database-name: "inji_verify"
  database-schema: "verify"
