version: '3.8'

services:
  inji-verify:
    image: mosipid/inji-verify:latest
    ports:
      - "80:80"
    environment:
      - INTERNET_CONNECTIVITY_CHECK_ENDPOINT=https://dns.google/
      - INTERNET_CONNECTIVITY_CHECK_TIMEOUT=10000