apiVersion: v2
name: inji-verify-service
description: A Helm chart for MOSIP inji verify service module
type: application
version: 0.12.3-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - inji-verify-service
maintainers:
  - email: info@mosip.io
    name: MOSIP
