apiVersion: v2
name: injiverify
description: A Helm chart for MOSIP injiverify module
type: application
version: 0.10.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - inji-verify
maintainers:
  - email: info@mosip.io
    name: MOSIP
